cabal-version: 2.4
name:          flickr-filter
version:       0.1.0.0
author:        Andrew Maier
maintainer:    andrew@maier.name

library
    exposed-modules:  FlickrFilter
    hs-source-dirs:   .
    default-language: Haskell2010
    build-depends:
          base          >= 4
        , aeson         >= 1.5
        , bytestring    >= 0.10
        , pandoc-types  >= 1.22
        , process       >= 1.6
        , text          >= 1.0

executable flickr-filter
    main-is:          Main.hs
    other-modules:    FlickrFilter
    hs-source-dirs:   .
    GHC-Options:      -threaded -rtsopts -with-rtsopts=-N
    default-language: Haskell2010
    build-depends:
          base          >= 4
        , aeson         >= 1.5
        , bytestring    >= 0.10
        , flickr-filter
        , pandoc-types  >= 1.22
        , process       >= 1.6
        , text          >= 1.0

